
import React from 'react';
import { LayoutGrid, Zap, Droplets, Trash2, Flame, Search, FileText, AlertCircle, ShieldCheck } from 'lucide-react';
import { Department, Language, CityAlert, Bill, UserProfile, SupportContact } from './types';

export const DEPARTMENTS: Department[] = [
  {
    id: 'eb',
    name: 'Electricity Board',
    icon: 'Zap',
    services: ['New Connection', 'Billing Issue', 'Meter Fault', 'Load Change', 'Other']
  },
  {
    id: 'water',
    name: 'Water Supply & Sewage',
    icon: 'Droplets',
    services: ['Water Connection', 'Sewage Block', 'Pipeline Leak', 'Bill Payment', 'Other']
  },
  {
    id: 'gas',
    name: 'Gas Distribution',
    icon: 'Flame',
    services: ['New Connection', 'Refill Booking', 'Leakage Complaint', 'Address Change', 'Other']
  },
  {
    id: 'municipal',
    name: 'Municipal Corp',
    icon: 'Trash2',
    services: ['Waste Management', 'Birth/Death Cert', 'Property Tax', 'Street Light', 'Other']
  }
];

export const MOCK_ALERTS: CityAlert[] = [
  { id: 'AL-01', type: 'Power', severity: 'Critical', ward: '12', message: 'Planned maintenance in Ward 12 from 2PM - 5PM.' },
  { id: 'AL-02', type: 'Water', severity: 'Warning', ward: 'Global', message: 'Low pressure expected in Central Zone due to pipeline repair.' },
  { id: 'AL-03', type: 'Civic', severity: 'Info', ward: '12', message: 'Mobile Health Camp today at Gandhi Park (Ward 12).' }
];

export const APP_CONFIG = {
  TITLE: 'AAZHI',
  SUBTITLE: 'Smart Urban Digital Helpdesk Assistant (SUVIDHA)',
  TAGLINE: 'Accessible. Transparent. Efficient.'
};


export const MOCK_USER_PROFILE: UserProfile = {
  id: 'CIT-9921',
  name: 'Arun Kumar',
  mobile: '9876543210',
  aadhaar: '8888 7777 9821',
  address: '12/B, Gandhi Nagar, Peelamedu, Coimbatore',
  ward: '12',
  zone: 'Central',
  consumerIds: {
    elec: 'EB-10098745',
    water: 'WT-554422',
    gas: 'GS-888999'
  }
};

export const MOCK_BILLS: Bill[] = [
  { id: 'BILL-FEB-26', consumerId: 'EB-10098745', serviceType: 'Electricity', amount: 1452, units: '240', month: 'Feb', year: '2026', status: 'Pending', dueDate: '2026-02-25', cycle: 'FEB-2026', readings: { current: 1240, previous: 1000 } },
  { id: 'BILL-JAN-26', consumerId: 'EB-10098745', serviceType: 'Electricity', amount: 1200, units: '210', month: 'Jan', year: '2026', status: 'Paid', dueDate: '2026-01-25', cycle: 'JAN-2026', readings: { current: 1000, previous: 790 }, paymentDate: '2026-01-24' },
  { id: 'BILL-DEC-25', consumerId: 'EB-10098745', serviceType: 'Electricity', amount: 1350, units: '230', month: 'Dec', year: '2025', status: 'Paid', dueDate: '2025-12-25', cycle: 'DEC-2025', readings: { current: 790, previous: 560 }, paymentDate: '2025-12-10' },
  { id: 'BILL-NOV-25', consumerId: 'EB-10098745', serviceType: 'Electricity', amount: 1100, units: '190', month: 'Nov', year: '2025', status: 'Paid', dueDate: '2025-11-25', cycle: 'NOV-2025', readings: { current: 560, previous: 370 }, paymentDate: '2025-11-20' },
];

export const PREDEFINED_ISSUES: Record<string, string[]> = {
  eb: ['Meter not working', 'Wrong bill amount', 'Power outage', 'Voltage fluctuation', 'Connection problem'],
  water: ['No water supply', 'Dirty water', 'Pipeline leak', 'Sewage block', 'New connection delay'],
  gas: ['Gas leak (Urgent)', 'Cylinder not delivered', 'Subsidy not received', 'Meter fault'],
  municipal: ['Garbage not collected', 'Street light not working', 'Dead animal removal', 'Property tax issue']
};

export const AREA_SUPPORT_CONTACTS: SupportContact[] = [
  { department: 'Electricity (Ward 12)', phone: '0422-2544001', area: '12', isEmergency: true },
  { department: 'Water Supply (Ward 12)', phone: '0422-2544102', area: '12' },
  { department: 'Sanitation (Ward 12)', phone: '98422 11223', area: '12' },
  { department: 'Central Helpdesk', phone: '1800 425 1111', area: 'Global' }
];

export const MOCK_REQUESTS = [
  { id: 'AZ-1001', type: 'New Connection', department: 'Electricity Board', citizenName: 'Arun Kumar', citizenId: 'CIT-9921', status: 'Pending', timestamp: '2024-05-15 10:30', details: 'Phase 3 connection for residential property.', issueCategory: 'BILLING_ERROR', ward: '12' },
  { id: 'AZ-1002', type: 'Pipeline Leak', department: 'Water Supply', citizenName: 'Priya S', citizenId: 'CIT-8811', status: 'Resolved', timestamp: '2024-05-14 14:20', details: 'Leak reported near main road junction.', issueCategory: 'PIPE_LEAK', ward: '10' },
  { id: 'AZ-1003', type: 'Waste Management', department: 'Municipal Corp', citizenName: 'John Doe', citizenId: 'CIT-7722', status: 'In Progress', timestamp: '2024-05-15 09:15', details: 'Regular garbage pickup missed for 3 days.', issueCategory: 'GARBAGE_COLLECTION', ward: '12' }
];


export const LANGUAGES_CONFIG = [
  { code: Language.ENGLISH, label: 'English', name: 'English' },
  { code: Language.ASSAMESE, label: 'অসমীয়া', name: 'Assamese' },
  { code: Language.BENGALI, label: 'বাংলা', name: 'Bengali' },
  { code: Language.BODO, label: 'बर\'/बड़ो', name: 'Bodo' },
  { code: Language.DOGRI, label: 'डोगरी', name: 'Dogri' },
  { code: Language.GUJARATI, label: 'ગુજરાતી', name: 'Gujarati' },
  { code: Language.HINDI, label: 'हिन्दी', name: 'Hindi' },
  { code: Language.KANNADA, label: 'ಕನ್ನಡ', name: 'Kannada' },
  { code: Language.KASHMIRI, label: 'کأشُر', name: 'Kashmiri', rtl: true },
  { code: Language.KONKANI, label: 'कोंकणी', name: 'Konkani' },
  { code: Language.MAITHILI, label: 'मैथिली', name: 'Maithili' },
  { code: Language.MALAYALAM, label: 'മലയാളം', name: 'Malayalam' },
  { code: Language.MANIPURI, label: 'ꯃꯤꯇꯩ ꯂꯣꯟ', name: 'Manipuri' },
  { code: Language.MARATHI, label: 'मराठी', name: 'Marathi' },
  { code: Language.NEPALI, label: 'नेपाली', name: 'Nepali' },
  { code: Language.ODIA, label: 'ଓଡ଼ିଆ', name: 'Odia' },
  { code: Language.PUNJABI, label: 'ਪੰਜਾਬੀ', name: 'Punjabi' },
  { code: Language.SANSKRIT, label: 'संस्कृतम्', name: 'Sanskrit' },
  { code: Language.SANTALI, label: 'ᱥᱟᱱᱛᱟᱲᱤ', name: 'Santali' },
  { code: Language.SINDHI, label: 'سنڌي', name: 'Sindhi', rtl: true },
  { code: Language.TAMIL, label: 'தமிழ்', name: 'Tamil' },
  { code: Language.TELUGU, label: 'తెలుగు', name: 'Telugu' },
  { code: Language.URDU, label: 'اُردُو', name: 'Urdu', rtl: true }
];

const BASE_TRANSLATIONS = {
  welcome: "Welcome",
  loginSubtitle: "Smart Urban Digital Helpdesk Assistant",
  enterId: "Enter Aadhaar Number or Official ID",
  aadhaarHint: "Citizens enter 12-digit Aadhaar. Officials use registered Department ID.",
  continue: "Continue",
  otpVerification: "Verification OTP",
  otpHint: "A 6-digit code has been sent to your Aadhaar-linked mobile.",
  loginCitizen: "Login as Citizen",
  officialPassword: "Official Password",
  accessAdmin: "Access Admin Panel",
  backToLang: "Back to Language Selection",
  adminDashboard: "Dashboard Overview",
  adminRequests: "Citizen Requests",
  adminComplaints: "Manage Complaints",
  welcomeBack: "Welcome back",
  citizensServed: "Citizens Served",
  pendingRequests: "Pending Requests",
  slaMet: "SLA Met",
  avgFeedback: "Avg Feedback",
  deptPerformance: "Department Performance",
  serviceDistribution: "Service Distribution",
  activeApps: "Active Applications",
  logout: "Logout Session",
  statusActive: "Cloud Sync Active",
  sysStatus: "System Status",
  liveAlerts: "Live City Alerts",
  privacyShield: "Privacy Shield",
  waitMsg: "Wait Time",
  tokenIssued: "Token Issued",
  selfService: "Self Service",
  counterHelp: "Counter Help",
  scanAssistant: "Scanning Assistant",
  // Electricity Module
  elecServices: "Electricity Services",
  officialPortal: "Official TANGEDCO / TNPDCL Portal",
  quickPay: "Quick Pay",
  quickPayDesc: "Pay instantly with just your Service Number. No password or registration required.",
  consumerLogin: "Consumer Login",
  consumerLoginDesc: "Log in to view bill history and download receipts.",
  startPayment: "Start Payment",
  secureLogin: "Secure Login",
  billCalculator: "Bill Calculator",
  tariffDetails: "Tariff Details",
  downloadReceipt: "Download Receipt",
  appDownload: "TANGEDCO App",
  fraudAlert: "Fraud Awareness Alert",
  fraudMsg: "TANGEDCO never asks for OTPs via SMS/WhatsApp. Pay only through official Kiosks.",
  backToUtils: "Back to Utilities",
  calcHeading: "Bill Calculator",
  calcSub: "Estimate your upcoming electricity charges.",
  connType: "Connection Type",
  domestic: "Domestic",
  commercial: "Commercial",
  unitsConsumed: "Units Consumed (kWh)",
  calculate: "Calculate",
  estCharge: "Estimated Charge",
  includesFixed: "Includes fixed charges. Actual bill may vary.",
  details: "Details",
  enterServiceNo: "Enter Service Connection Number",
  fetchBill: "Fetch Bill Details",
  totalPending: "Total Outstanding",
  dueDate: "Due Date",
  payNow: "Pay Now",
  paymentSuccess: "Payment Successful!",
  printReceipt: "Print Receipt",
  receipt: "Receipt",
  transId: "Transaction ID",
  consumerNo: "Service No",
  consumerName: "Consumer Name",
  billAmount: "Bill Amount",
  receiptHeader: "Tamil Nadu Generation and Distribution Corporation Limited",
  eReceipt: "E-Receipt",
  receiptDisclaimer: "Receipt issued subject to confirmation of online payment credit in TANGEDCO’s bank account.",
  paymentMode: "Payment Mode",
  back: "Back",
  // Dashboard Home
  namaste: "Namaste",
  eKycVerified: "e-KYC Verified",
  aadhaar: "Aadhaar",
  ward: "Ward",
  wardsupport: "Ward Support Officer",
  newRequest: "New Request",
  newRequestDesc: "Connections, Certificates & Civic Services",
  start: "Start",
  payBills: "Pay Bills",
  payBillsDesc: "Water, Elec, Gas & Property Tax",
  pay: "Pay",
  zeroDocVault: "Zero-Document Vault",
  docVaultDesc: "DigiLocker Linked • 3 Verified Documents Ready",
  viewDocs: "View Documents",
  // Sidebar
  navHome: "Home",
  navServices: "Services",
  navPayBills: "Pay Bills",
  navHelp: "Complaints",
  navHistory: "History",
  navAssistant: "Assistant",
  navExit: "Exit",
  welcomeUser: "Welcome",
  terminalId: "Terminal ID",
  // Alerts Panel
  localAlerts: "Local Alerts",
  live: "LIVE",
  cityWide: "City Wide",
  // Analytics
  consumptionTrends: "Consumption Trends",
  elecWaterUsage: "Electricity & Water Usage",
  power: "Power",
  water: "Water",
  smartTip: "Smart Tip",
  tipContent: "Your usage peaks in May. Switching to 5-Star rated ACs can save ₹400/month.",
  // Disruption Map
  liveMap: "Live Disruption Map",
  iotSensor: "IoT Sensor Network • Realtime",
  powerOutage: "Power Outage",
  waterCut: "Water Cut",
  normal: "Normal",
  estRestore: "Est. Restore",
  // Dept Names
  deptEB: "Electricity Board",
  deptWater: "Water Supply & Sewage",
  deptGas: "Gas Distribution",
  deptMunicipal: "Municipal Corp",
  // Service Mode Selector
  modeHeading: "How would you like to proceed?",
  modeSub: "Choose a processing mode for",
  modeSelf: "Self Service",
  modeSelfDesc: "Fastest. Digital Processing. Immediate Token.",
  modeSelfWait: "EST. WAIT: 0 MINS",
  modeCounter: "Counter Help",
  modeCounterDesc: "Get a Token for physical counter assistance.",
  modeCounterWait: "EST. WAIT: 15 MINS",
  goBack: "Go Back",
  recommended: "Recommended",
  // Form Wizard
  reportIssue: "Report Issue",
  appWizard: "Application Wizard",
  applicantName: "Applicant Name",
  contactNumber: "Contact Number",
  nextStep: "Next Step",
  docProvHeading: "How would you like to provide documents?",
  fetchDL: "Fetch from DigiLocker",
  fetchDLDesc: "Recommended • Instant Verification",
  uploadMan: "Upload Manually",
  uploadManDesc: "Scan Physical Copies",
  or: "OR",
  review: "Review",
  submitReq: "Submit Request",
  promptDetails: "Please confirm your personal details.",
  promptScan: "We need to verify your identity. Please scan your Aadhaar.",
  promptIssue: "Optional: Upload a photo of the issue.",
  promptReview: "Review details before submission.",
  // Success
  reqFiled: "Request Filed!",
  smsSent: "A confirmation SMS has been sent to +91",
  yourToken: "Your Service Token",
  scanQr: "Scan QR to continue on Mobile",
  finish: "Finish & Clear Session",
  // KioskUI
  oneTap: "One-tap utility payments for a smarter life.",
  consumerLabel: "Consumer Number",
  connectionId: "Connection ID",
  customerId: "Customer ID",
  cancel: "Cancel",
  gas: "Gas",
  // Receipt
  elecBill: "Electricity Bill",
  billMonthYear: "Bill Month / Year",
  receiptNo: "Receipt No",
  receiptDate: "Receipt Date",
  amountDebited: "Amount Debited",
  bankTxnNo: "Bank Transaction No",
  bankAuthId: "Bank Authorisation Id",
  compGenReceipt: "This is a computer generated receipt.",
  // Elec Module
  upcoming: "Coming Soon...",
  loginHeading: "Consumer Login",
  loginSub: "Access bill history & manage your connection.",
  serviceNoOrUser: "Service No / User ID",
  password: "Password",
  loginBtn: "Login",
  verifying: "Verifying...",
  myConnection: "My Connection",
  paymentDue: "Payment Due",
  totalOutstanding: "Total Outstanding",
  payBillNow: "Pay Bill Now",
  billingCycle: "Billing Cycle",
  recentTxns: "Recent Transactions",
  downloadStmt: "Download Statement",
  downloadStmtDesc: "Get detailed statement for last 6 months",
  consumptionAnalysis: "Consumption Analysis",
  consumptionAnalysisDesc: "View graphs of your power usage",
  secureEnv: "Secure Environment. Keyboard input is monitored for safety."
};

export const TRANSLATIONS: Record<Language, typeof BASE_TRANSLATIONS> = {
  [Language.ENGLISH]: BASE_TRANSLATIONS,
  [Language.TAMIL]: {
    ...BASE_TRANSLATIONS,
    welcome: "வரவேற்கிறோம்",
    loginSubtitle: "ஸ்மார்ட் நகர்ப்புற டிஜிட்டல் உதவி மையம்",
    enterId: "ஆதார் எண் அல்லது அதிகாரப்பூர்வ ஐடியை உள்ளிடவும்",
    aadhaarHint: "குடிமக்கள் 12 இலக்க ஆதாரை உள்ளிடவும். அதிகாரிகள் துறை ஐடியைப் பயன்படுத்தவும்.",
    continue: "தொடரவும்",
    otpVerification: "சரிபார்ப்பு OTP",
    otpHint: "உங்கள் ஆதாருடன் இணைக்கப்பட்ட மொபைலுக்கு 6 இலக்க குறியீடு அனுப்பப்பட்டுள்ளது.",
    loginCitizen: "குடிமகனாக உள்நுழையவும்",
    officialPassword: "அதிகாரப்பூர்வ கடவுச்சொல்",
    accessAdmin: "நிர்வாக குழுவை அணுகவும்",
    backToLang: "மொழித் தேர்வுக்குச் செல்லவும்",
    adminDashboard: "நிர்வாக மேலோட்டம்",
    adminRequests: "குடிமக்கள் கோரிக்கைகள்",
    adminComplaints: "புகார்களை நிர்வகிக்கவும்",
    welcomeBack: "மீண்டும் வருக",
    citizensServed: "சேவையளிக்கப்பட்ட குடிமக்கள்",
    pendingRequests: "நிலுவையில் உள்ள கோரிக்கைகள்",
    slaMet: "SLA எட்டப்பட்டது",
    avgFeedback: "சராசரி கருத்து",
    deptPerformance: "துறை செயல்திறன்",
    serviceDistribution: "சேவை விநியோகம்",
    activeApps: "செயலில் உள்ள விண்ணப்பங்கள்",
    logout: "வெளியேறவும்",
    statusActive: "கிளவுட் ஒத்திசைவு செயலில் உள்ளது",
    sysStatus: "கணினி நிலை",
    liveAlerts: "நேரடி விழிப்பூட்டல்கள்",
    privacyShield: "தனியுரிமை கவசம்",
    waitMsg: "காத்திருப்பு நேரம்",
    tokenIssued: "டோக்கன் வழங்கப்பட்டது",
    selfService: "சுய சேவை",
    counterHelp: "உதவி மையம்",
    scanAssistant: "ஸ்கேனிங் உதவியாளர்",
    // Elec
    elecServices: "மின்சார சேவைகள்",
    officialPortal: "அதிகாரப்பூர்வ TANGEDCO போர்டல்",
    quickPay: "விரைவு கட்டணம்",
    quickPayDesc: "சேவை எண்ணைப் பயன்படுத்தி உடனடியாக பணம் செலுத்தவும்.",
    consumerLogin: "நுகர்வோர் உள்நுழைவு",
    consumerLoginDesc: "பில் வரலாறு மற்றும் ரசீதுகளைப் பார்க்கவும்.",
    startPayment: "கட்டணத்தை தொடங்கவும்",
    secureLogin: "பாதுகாப்பான உள்நுழைவு",
    billCalculator: "பில் கால்குலேட்டர்",
    tariffDetails: "கட்டண விவரங்கள்",
    downloadReceipt: "ரசீது பதிவிறக்கவும்",
    appDownload: "மொபைல் செயலி",
    fraudAlert: "மோசடி விழிப்புணர்வு",
    fraudMsg: "TANGEDCO ஒருபோதும் OTP கேட்பதில்லை. அதிகாரப்பூர்வ மையங்களில் மட்டும் செலுத்தவும்.",
    backToUtils: "திரும்ப",
    calcHeading: "பில் கால்குலேட்டர்",
    calcSub: "உங்கள் மின்சார கட்டணத்தை மதிப்பிடவும்.",
    connType: "இணைப்பு வகை",
    domestic: "வீட்டு உபயோகம்",
    commercial: "வணிகம்",
    unitsConsumed: "பயன்படுத்திய அலகுகள் (Units)",
    calculate: "கணக்கிடு",
    estCharge: "மதிப்பிடப்பட்ட கட்டணம்",
    includesFixed: "நிலையான கட்டணங்கள் உட்பட.",
    details: "விவரங்கள்",
    enterServiceNo: "சேவை எண்ணை உள்ளிடவும்",
    fetchBill: "பில் விவரங்களைப் பெறவும்",
    totalPending: "மொத்த நிலுவை",
    dueDate: "கெடு தேதி",
    payNow: "இப்போதே செலுத்தவும்",
    paymentSuccess: "கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது!",
    printReceipt: "ரசீது அச்சிடவும்",
    receipt: "ரசீது",
    transId: "பரிவர்த்தனை ஐடி",
    consumerNo: "சேவை எண்",
    consumerName: "நுகர்வோர் பெயர்",
    billAmount: "பில் தொகை",
    receiptHeader: "தமிழ்நாடு மின் உற்பத்தி மற்றும் பகிர்மானக் கழகம்",
    eReceipt: "மின் ரசீது",
    receiptDisclaimer: "ஆன்லைன் கட்டணம் வரவு வைக்கப்பட்ட பிறகு ரசீது உறுதிப்படுத்தப்படும்.",
    paymentMode: "கட்டண முறை",
    back: "திரும்ப",
    // Dashboard
    namaste: "வணக்கம்",
    eKycVerified: "e-KYC சரிபார்க்கப்பட்டது",
    aadhaar: "ஆதார்",
    ward: "வார்டு",
    wardsupport: "வார்டு உதவி அலுவலர்",
    newRequest: "புதிய கோரிக்கை",
    newRequestDesc: "இணைப்புகள், சான்றிதழ்கள் & குடிமை சேவைகள்",
    start: "தொடங்க",
    payBills: "பில்கள் செலுத்த",
    payBillsDesc: "நீர், மின்சாரம், எரிவாயு & சொத்து வரி",
    pay: "செலுத்த",
    zeroDocVault: "ஆவண காப்பகம்",
    docVaultDesc: "DigiLocker இணைக்கப்பட்டுள்ளது • 3 சரிபார்க்கப்பட்ட ஆவணங்கள் தயாராக உள்ளன",
    viewDocs: "ஆவணங்களைப் பார்க்கவும்",
    // Sidebar
    navHome: "முகப்பு",
    navServices: "சேவைகள்",
    navPayBills: "கட்டணம் செலுத்த",
    navHelp: "புகார்கள்",
    navHistory: "வரலாறு",
    navAssistant: "உதவியாளர்",
    navExit: "வெளியேறு",
    welcomeUser: "வரவேற்கிறோம்",
    terminalId: "முனனைய ஐடி",
    // Alerts
    localAlerts: "உள்ளூர் எச்சரிக்கைகள்",
    live: "நேரலை",
    cityWide: "நகரம் முழுவதும்",
    // Analytics
    consumptionTrends: "நுகர்வு போக்குகள்",
    elecWaterUsage: "மின்சாரம் & நீர் பயன்பாடு",
    power: "மின்சாரம்",
    water: "தண்ணீர்",
    smartTip: "ஸ்மார்ட் டிப்",
    tipContent: "மே மாதத்தில் உங்கள் பயன்பாடு அதிகமாக உள்ளது. 5-நட்சத்திர AC-க்கு மாறுவது உங்களுக்கு ₹400/மாதம் சேமிக்கலாம்.",
    // Disruption
    liveMap: "நேரடி இடையூறு வரைபடம்",
    iotSensor: "IoT சென்சார் நெட்வொர்க் • நிகழ்நேரம்",
    powerOutage: "மின்வெட்டு",
    waterCut: "தண்ணீர் வரத்து இல்லை",
    normal: "இயல்பு",
    estRestore: "மீட்பு நேரம்",
    // Depts
    deptEB: "மின்சார வாரியம்",
    deptWater: "குடிநீர் வழங்கல் & வடிகால்",
    deptGas: "எரிவாயு விநியோகம்",
    deptMunicipal: "மாநகராட்சி",
    // Mode
    modeHeading: "எப்படித் தொடர விரும்புகிறீர்கள்?",
    modeSub: "செயலாக்க முறையைத் தேர்ந்தெடுக்கவும்:",
    modeSelf: "சுய சேவை",
    modeSelfDesc: "வேகமானது. டிஜிட்டல் செயலாக்கம். உடனடி டோக்கன்.",
    modeSelfWait: "காத்திருப்பு: 0 நிமிடம்",
    modeCounter: "உதவி மையம்",
    modeCounterDesc: "நேரடி உதவிக்கான டோக்கனைப் பெறுங்கள்.",
    modeCounterWait: "காத்திருப்பு: 15 நிமிடம்",
    goBack: "திரும்ப",
    recommended: "பரிந்துரைக்கப்படுகிறது",
    // Form
    reportIssue: "புகார் அளிக்கவும்",
    appWizard: "விண்ணப்ப வழிகாட்டி",
    applicantName: "விண்ணப்பதாரர் பெயர்",
    contactNumber: "தொடர்பு எண்",
    nextStep: "அடுத்த படி",
    docProvHeading: "ஆவணங்களை எவ்வாறு வழங்க விரும்புகிறீர்கள்?",
    fetchDL: "DigiLocker-லிருந்து பெறவும்",
    fetchDLDesc: "பரிந்துரைக்கப்படுகிறது • உடனடி சரிபார்ப்பு",
    uploadMan: "கைமுறையாக பதிவேற்றவும்",
    uploadManDesc: "நகல்களை ஸ்கேன் செய்யவும்",
    or: "அல்லது",
    review: "மதிப்பாய்வு",
    submitReq: "கோரிக்கையை சமர்ப்பிக்கவும்",
    promptDetails: "உங்கள் தனிப்பட்ட விவரங்களை உறுதிப்படுத்தவும்.",
    promptScan: "உங்கள் அடையாளத்தைச் சரிபார்க்க வேண்டும். ஆதாரை ஸ்கேன் செய்யவும்.",
    promptIssue: "விருப்பத்தேர்வு: புகாருக்கான புகைப்படத்தைப் பதிவேற்றவும்.",
    promptReview: "சமர்ப்பிக்கும் முன் விவரங்களை மதிப்பாய்வு செய்யவும்.",
    // Success
    reqFiled: "கோரிக்கை பதிவு செய்யப்பட்டது!",
    smsSent: "உறுதிப்படுத்தல் SMS அனுப்பப்பட்டது: +91",
    yourToken: "உங்கள் சேவை டோக்கன்",
    scanQr: "மொபைலில் தொடர QR-ஐ ஸ்கேன் செய்யவும்",
    finish: "முடித்து வெளியேறவும்",
    // KioskUI
    oneTap: "சிறந்த வாழ்க்கைக்கான விரைவான பயன்பாட்டு கட்டணங்கள்.",
    consumerLabel: "நுகர்வோர் எண்",
    connectionId: "இணைப்பு ஐடி",
    customerId: "வாடிக்கையாளர் ஐடி",
    cancel: "ரத்து செய்",
    gas: "எரிவாயு",
    // Receipt
    elecBill: "மின்சார ரசீது",
    billMonthYear: "பில் மாதம் / ஆண்டு",
    receiptNo: "ரசீது எண்",
    receiptDate: "ரசீது தேதி",
    amountDebited: "கழிக்கப்பட்ட தொகை",
    bankTxnNo: "வங்கி பரிவர்த்தனை எண்",
    bankAuthId: "வங்கி அங்கீகார ஐடி",
    compGenReceipt: "இது கணினி மூலம் உருவாக்கப்பட்ட ரசீது.",
    // Elec Module
    upcoming: "விரைவில்...",
    loginHeading: "நுகர்வோர் உள்நுழைவு",
    loginSub: "பில் வரலாற்றை அணுகவும் மற்றும் இணைப்பை நிர்வகிக்கவும்.",
    serviceNoOrUser: "சேவை எண் / பயனர் ஐடி",
    password: "கடவுச்சொல்",
    loginBtn: "உள்நுழைய",
    verifying: "சரிபார்க்கிறது...",
    myConnection: "எனது இணைப்பு",
    paymentDue: "செலுத்த வேண்டிய தொகை",
    totalOutstanding: "மொத்த நிலுவை",
    payBillNow: "இப்போதே பில் செலுத்தவும்",
    billingCycle: "பில்லிங் சுழற்சி",
    recentTxns: "சமீபத்திய பரிவர்த்தனைகள்",
    downloadStmt: "அறிக்கை பதிவிறக்கவும்",
    downloadStmtDesc: "கடந்த 6 மாதங்களுக்கான விரிவான அறிக்கையைப் பெறுங்கள்",
    consumptionAnalysis: "நுகர்வு பகுப்பாய்வு",
    consumptionAnalysisDesc: "உங்கள் மின் பயன்பாட்டின் வரைபடங்களைப் பார்க்கவும்",
    secureEnv: "பாதுகாப்பான சூழல். உள்ளீடு கண்காணிக்கப்படுகிறது."
  },
  [Language.HINDI]: {
    ...BASE_TRANSLATIONS,
    welcome: "स्वागत है",
    loginSubtitle: "स्मार्ट शहरी डिजिटल सहायता केंद्र",
    continue: "जारी रखें",
    loginCitizen: "लॉगिन करें",
    officialPassword: "पासवर्ड",
    accessAdmin: "एडमिन",
    backToLang: "वापस",
    adminDashboard: "डैशबोर्ड",
    adminRequests: "अनुरোধ",
    adminComplaints: "शिकायतें",
    elecServices: "विद्युत सेवाएं",
    officialPortal: "आधिकारिक TANGEDCO पोर्टल",
    quickPay: "त्वरित भुगतान",
    quickPayDesc: "बिना पासवर्ड के तुरंत बिल भरें।",
    consumerLogin: "उपभोक्ता लॉगिन",
    consumerLoginDesc: "बिल इतिहास और रसीद देखें।",
    startPayment: "भुगतान शुरू करें",
    secureLogin: "सुरक्षित लॉगिन",
    billCalculator: "बिल कैलकुलेटर",
    tariffDetails: "दर विवरण",
    downloadReceipt: "रसीद डाउनलोड",
    appDownload: "मोबाइल ऐप",
    fraudAlert: "धोखाधड़ी चेतावनी",
    fraudMsg: "TANGEDCO कभी भी OTP नहीं मांगता। केवल आधिकारिक कियोस्क पर भुगतान करें।",
    backToUtils: "वापस",
    calcHeading: "बिल कैलकुलेटर",
    calcSub: "अपने बिजली बिल का अनुमान लगाएं。",
    connType: "कनेक्शन प्रकार",
    domestic: "घरेलू",
    commercial: "व्यावसायिक",
    unitsConsumed: "खपत यूनिट (kWh)",
    calculate: "गणना करें",
    estCharge: "अनुमानित लागत",
    includesFixed: "निश्चित शुल्क शामिल है।",
    details: "विवरण",
    enterServiceNo: "सेवा संख्या दर्ज करें",
    fetchBill: "बिल विवरण प्राप्त करें",
    totalPending: "कुल बकाया",
    dueDate: "नियत तारीख",
    payNow: "अभी भुगतान करें",
    paymentSuccess: "भुगतान सफल!",
    printReceipt: "रसीद प्रिंट करें",
    receipt: "रसीद",
    transId: "लेनदेन आईडी",
    consumerNo: "सेवा संख्या",
    consumerName: "उपभोक्ता का नाम",
    billAmount: "बिल राशि",
    receiptHeader: "तमिलनाडु उत्पादन और वितरण निगम लिमिटेड",
    eReceipt: "ई-रसीद",
    receiptDisclaimer: "TANGEDCO के बैंक खाते में ऑनलाइन भुगतान जमा होने की पुष्टि के अधीन रसीद जारी की गई।",
    paymentMode: "भुगतान मोड",
    back: "वापस",
    // Dashboard
    namaste: "नमस्ते",
    eKycVerified: "ई-केवाईसी सत्यापित",
    aadhaar: "आधार",
    ward: "वार्ड",
    wardsupport: "वार्ड सहायता अधिकारी",
    newRequest: "नया अनुरोध",
    newRequestDesc: "कनेक्शन, प्रमाण पत्र और नागरिक सेवाएं",
    start: "शुरू करें",
    payBills: "बिल भुगतान",
    payBillsDesc: "पानी, बिजली, गैस और संपत्ति कर",
    pay: "भुगतान करें",
    viewDocs: "दस्तावेज़ देखें",
    // Sidebar
    navHome: "होम",
    navServices: "सेवाएं",
    navPayBills: "बिल भुगतान",
    navHelp: "शिकायतें",
    navHistory: "इतिहास",
    navAssistant: "सहायक",
    navExit: "बाहर निकलें",
    welcomeUser: "स्वागत है",
    terminalId: "टर्मिनल आईडी",
    // Alerts
    localAlerts: "स्थानीय अलर्ट",
    live: "लाइव",
    cityWide: "पूरे शहर में",
    // Analytics
    consumptionTrends: "खपत के रुझान",
    elecWaterUsage: "बिजली और पानी का उपयोग",
    power: "बिजली",
    water: "पानी",
    smartTip: "स्मार्ट टिप",
    tipContent: "मई में आपका उपयोग चरम पर होता है। 5-स्टार एसी पर स्विच करने से ₹400/माह बच सकते हैं।",
    // Disruption
    liveMap: "लाइव व्यवधान मानचित्र",
    iotSensor: "IoT सेंसर नेटवर्क • रीयल-टाइम",
    powerOutage: "बिजली कटौती",
    waterCut: "पानी की कटौती",
    normal: "सामान्य",
    estRestore: "अनुमानित बहाली",
    // Depts
    deptEB: "बिजली बोर्ड",
    deptWater: "जल आपूर्ति और सीवेज",
    deptGas: "गैस वितरण",
    deptMunicipal: "नगर निगम",
    // Mode
    modeHeading: "आप कैसे आगे बढ़ना चाहेंगे?",
    modeSub: "प्रसंस्करण मोड चुनें:",
    modeSelf: "स्वयं सेवा",
    modeSelfDesc: "सबसे तेज़। डिजिटल प्रोसेसिंग। तत्काल टोकन।",
    modeSelfWait: "प्रतीक्षा: 0 मिनट",
    modeCounter: "काउंटर सहायता",
    modeCounterDesc: "भौतिक काउंटर सहायता के लिए टोकन प्राप्त करें।",
    modeCounterWait: "प्रतीक्षा: 15 मिनट",
    goBack: "वापस जाएं",
    recommended: "अनुशंसित",
    // Form
    reportIssue: "समस्या की रिपोर्ट करें",
    appWizard: "आवेदन विज़ार्ड",
    applicantName: "आवेदक का नाम",
    contactNumber: "संपर्क नंबर",
    nextStep: "अगला चरण",
    docProvHeading: "आप दस्तावेज़ कैसे प्रदान करना चाहेंगे?",
    fetchDL: "डिजीलॉकर से प्राप्त करें",
    fetchDLDesc: "अनुशंसित • तत्काल सत्यापन",
    uploadMan: "मैन्युअल रूप से अपलोड करें",
    uploadManDesc: "भौतिक प्रतियां स्कैन करें",
    or: "या",
    review: "समीक्षा",
    submitReq: "अनुरोध जमा करें",
    promptDetails: "कृपया अपने व्यक्तिगत विवरण की पुष्टि करें।",
    promptScan: "हमें आपकी पहचान सत्यापित करने की आवश्यकता है। कृपया अपना आधार स्कैन करें।",
    promptIssue: "वैकल्पिक: समस्या की एक तस्वीर अपलोड करें।",
    promptReview: "जमा करने से पहले विवरण की समीक्षा करें।",
    // Success
    reqFiled: "अनुरोध दर्ज किया गया!",
    smsSent: "एक पुष्टि एसएमएस +91 पर भेजा गया है",
    yourToken: "आपका सेवा टोकन",
    scanQr: "मोबाइल पर जारी रखने के लिए QR स्कैन करें",
    finish: "समाप्त करें और सत्र साफ़ करें",
    // KioskUI
    oneTap: "होशियार जीवन के लिए एक-टैप उपयोगिता भुगतान।",
    consumerLabel: "उपभोक्ता संख्या",
    connectionId: "कनेक्शन आईडी",
    customerId: "ग्राहक आईडी",
    cancel: "रद्द करें",
    gas: "गैस",
    // Receipt
    elecBill: "बिजली बिल",
    billMonthYear: "बिल महीना / वर्ष",
    receiptNo: "रसीद संख्या",
    receiptDate: "रसीद दिनांक",
    amountDebited: "नामे की गई राशि",
    bankTxnNo: "बैंक लेनदेन संख्या",
    bankAuthId: "बैंक प्राधिकरण आईडी",
    compGenReceipt: "यह कंप्यूटर जनित रसीद है।",
    // Elec Module
    upcoming: "जल्द आ रहा है...",
    loginHeading: "उपभोक्ता लॉगिन",
    loginSub: "बिल इतिहास देखें और कनेक्शन प्रबंधित करें।",
    serviceNoOrUser: "सेवा संख्या / यूजर आईडी",
    password: "पासवर्ड",
    loginBtn: "लॉगिन",
    verifying: "सत्यापन हो रहा है...",
    myConnection: "मेरा कनेक्शन",
    paymentDue: "भुगतान शेष",
    totalOutstanding: "कुल बकाया",
    payBillNow: "अभी भुगतान करें",
    billingCycle: "बिलिंग चक्र",
    recentTxns: "हालिया लेनदेन",
    downloadStmt: "विवरण डाउनलोड करें",
    downloadStmtDesc: "पिछले 6 महीनों का विस्तृत विवरण प्राप्त करें",
    consumptionAnalysis: "खपत विश्लेषण",
    consumptionAnalysisDesc: "अपने बिजली उपयोग के ग्राफ देखें",
    secureEnv: "सुरक्षित वातावरण। कीबोर्ड इनपुट की निगरानी की जाती है।"
  },
  [Language.ASSAMESE]: { ...BASE_TRANSLATIONS },
  [Language.BENGALI]: { ...BASE_TRANSLATIONS },
  [Language.BODO]: { ...BASE_TRANSLATIONS },
  [Language.DOGRI]: { ...BASE_TRANSLATIONS },
  [Language.GUJARATI]: { ...BASE_TRANSLATIONS },
  [Language.KANNADA]: { ...BASE_TRANSLATIONS },
  [Language.KASHMIRI]: { ...BASE_TRANSLATIONS },
  [Language.KONKANI]: { ...BASE_TRANSLATIONS },
  [Language.MAITHILI]: { ...BASE_TRANSLATIONS },
  [Language.MALAYALAM]: { ...BASE_TRANSLATIONS },
  [Language.MANIPURI]: { ...BASE_TRANSLATIONS },
  [Language.MARATHI]: { ...BASE_TRANSLATIONS },
  [Language.NEPALI]: { ...BASE_TRANSLATIONS },
  [Language.ODIA]: { ...BASE_TRANSLATIONS },
  [Language.PUNJABI]: { ...BASE_TRANSLATIONS },
  [Language.SANSKRIT]: { ...BASE_TRANSLATIONS },
  [Language.SANTALI]: { ...BASE_TRANSLATIONS },
  [Language.SINDHI]: { ...BASE_TRANSLATIONS },
  [Language.TELUGU]: { ...BASE_TRANSLATIONS },
  [Language.URDU]: { ...BASE_TRANSLATIONS }
};
